garymm/starflate

- WORKSPACE.bazel
- src/BUILD.bazel
- src/dummy_test.cpp
Change-Id: Ia3fbfa2b807e528d482a617687276e1682df0ac5
> Add boost-ut unit test library

- src/BUILD.bazel
- src/dummy_test.cpp
- src/huffman.hpp
- src/huffman_test.cpp
Change-Id: Ic80df8fc8a9c28d11895a247b732b00a14e22733
> Define Huffman code tree

- .clang-tidy
- .github/workflows/check.yml
- WORKSPACE.bazel
- src/huffman.hpp
- src/test/.clang-tidy
- src/test/BUILD.bazel
- src/test/huffman_bench.cpp
- third_party/google_benchmark.patch
Change-Id: Idbd62771e79c78e75cb1707c6027b1d94f99f322
> add google benchmark

- .bazelrc
- src/test/BUILD.bazel
- src/test/bench_results.md
- src/test/huffman_bench.cpp
- src/version/BUILD.bazel
- src/version/version.cpp
- src/version/version.hpp
- tools/bazel_workspace_status.sh
Change-Id: I7a8331e1e27f61dfa1c485f1c0c8cc3b9435be0f
> support build version, record benchmark results

- README.md
- WORKSPACE.bazel
Change-Id: I75bcf601a575c1ecb35bb387a1d17e28d72c885f
> Support for clangd compilation database.

- .vscode/extensions.json
- .vscode/settings.json
- README.md
Change-Id: I5364fb1aa8e95201256b73acc2f2b2e77dea649b
> VS Code settings

- src/detail/huffman_storage.hpp
- src/huffman.hpp
- src/test/huffman.cpp
Change-Id: I918bc6dbffa8430adc73b68038836658be860f4c
> Support `constexpr` construction of `code_table`

- src/test/bench_results.md
Change-Id: I5bd52d3efb8007e16d78e6f069a71a5d11f80dcf
> update bench results

- src/detail/huffman_storage.hpp
- src/huffman.hpp
- src/test/huffman.cpp
Change-Id: If872fa7ab47df0e8bb977fb6974696c12f29d5e5
> Make eot optional for `code_table`s

- .github/workflows/check.yml
- WORKSPACE.bazel
- toolchain/BUILD.bazel
Change-Id: I760e1e7d6bd4ab43c37cf48fdfe29bd08617c261
> Update `@bazel_bootlin` and enable sanitizers with GCC

- huffman/src/table.hpp
- huffman/test/table_from_frequencies_test.cpp
Change-Id: Ie2bed95b7a1d6faa93b7af09f3580ce54d686189
> Add deduction guide for `table` with C array arg

- huffman/test/table_from_frequencies_test.cpp
- src/decompress.hpp
- src/huffman.hpp
- src/test/huffman.cpp
- toolchain/std_expected_available.cpp
Change-Id: Idc5fc9878d4d956fa5bc8c20d5c572dd2e494179
> Use `[[maybe_unused]]` instead of `void` cast

- .clang-tidy
- huffman/src/code.hpp
- huffman/src/encoding.hpp
- huffman/src/table.hpp
- huffman/test/BUILD.bazel
- huffman/test/code_test.cpp
- huffman/test/table_find_code_test.cpp
Change-Id: Iefe03769ea3d56b116a2a97bf6a2b114cb98ea67
> Define `huffman::table::find(code, const_iterator)`

- huffman/test/BUILD.bazel
- src/test/BUILD.bazel
- toolchain/BUILD.bazel
Change-Id: I9fbb67ae4230a42e2e41841ded0e749862122e06
> set timeouts on tests

- .github/workflows/check.yml
Change-Id: I0110656605dea3678dded96f66cafc8e2daa7827
> Exclude `verbose-clang-tidy` config for pull requests

- WORKSPACE.bazel
Change-Id: Ic2dde15f5766a3e706cf29138030e604b4a385c9
> Upgrade to LLVM 16.0.4

- .vscode/settings.json
Change-Id: I48d11e3335324a210c61dfa5d1699a7de3e411f6
> fix clangd path

- huffman/BUILD.bazel
- huffman/huffman.hpp
- huffman/src/bit.hpp
- huffman/src/bit_span.hpp
- huffman/test/BUILD.bazel
- huffman/test/bit_span_test.cpp
for easy iteration of the bits in some data
Change-Id: I6f1dee0448ff071e9b820aa5a020120717b61ab2
> implement bit_span

- .bazelrc
- .github/workflows/check.yml
- .vscode/settings.json
- BUILD.bazel
- WORKSPACE.bazel
- toolchain/BUILD.bazel
- tools/BUILD.bazel
we only use one version of each so this is simpler
Change-Id: Iac008c1403710966bca47db958e627c7b079ea26
> rm version from toolchain names

- tools/bazel_workspace_status.sh
we are not using it and it fails in GitHub workflows
Change-Id: I6308dd5b7090f7ddea48921eab4b1d9b4278736c
> remove branch from workspace status script

- README.md
- huffman/src/bit.hpp
- huffman/src/bit_span.hpp
- huffman/src/code.hpp
- huffman/src/decode.hpp
- huffman/src/detail/base_view.hpp
- huffman/src/detail/iterator_interface.hpp
- huffman/src/detail/static_vector.hpp
- huffman/src/detail/table_node.hpp
- huffman/src/detail/table_storage.hpp
- huffman/src/encoding.hpp
- huffman/src/table.hpp
- huffman/test/bench.cpp
- huffman/test/bench_results.md
- huffman/test/bit_span_test.cpp
- huffman/test/bit_test.cpp
- huffman/test/code_test.cpp
- huffman/test/decode_test.cpp
- huffman/test/table_find_code_test.cpp
- huffman/test/table_from_contents_test.cpp
- huffman/test/table_from_data_test.cpp
- huffman/test/table_from_frequencies_test.cpp
- src/decompress.hpp
- version/version.cpp
- version/version.hpp
rename gpu_deflate -> starflate
Change-Id: Idde6233615ab528fd3d73c78a55d6a88df995d2a
> rename gpu_deflate -> starflate

- huffman/src/bit_span.hpp
Change-Id: I34772c33111e073f58d75c7949bea68dc232353a
> use bitset in bit_span::operator*

- huffman/src/bit_span.hpp
- huffman/test/bit_span_test.cpp
Change-Id: Id460151a080e8a1c55e382182e34e60eed71c78c
> handle non-byte aligned data with bit_span

- WORKSPACE.bazel
Change-Id: I916c03915e7319f42a4c8a0ca11106097d5b41db
> upgrade boost_ut

- .github/workflows/check.yml
- BUILD.bazel
- test_ut/BUILD.bazel
and remove it from code coverage reports.
Change-Id: I57311078b4a256b83e81341b456144d408d9e3c4
> set replacement `boost_ut` lib as testonly

- .bazelrc
- .github/workflows/ci.bazelrc
> use clang for coverage in CI

- src/decompress.hpp
Change-Id: Ie5ff9ebaffe3eff70e12fd52b608fc90468e650a
> bulk copy decomprssed data

- src/test/decompress_test.cpp
test decompress with an invalid header
Change-Id: I38d3105028247c4da00e9061dc5a806955a79d4e
> test decompress with an invalid header

- WORKSPACE.bazel
- tools/llvm_toolchain.bzl
- tools/llvm_toolchain_dependencies.bzl
update llvm toolchain repo
Change-Id: I033a4b201c72fe43e70702eed3c4098666398c1d
> update llvm toolchain repo
