WORKSPACE.bazel
We're going for speed, not portability :-)
=> build with "-march=native"

.github/workflows/check.yml, .github/workflows/ci.bazelrc, WORKSPACE.bazel
Enable a pre-merge check workflow that verifies //:print_hip_info run
and that all tests pass.
This commit also fixes an incorrect commit for the @bazel_bootlin
dependency.
Change-Id: I9f00399c5aa33b52d332e4b05261dfb4869d565e
=> Enable Github check workflow

.bazelrc, .clang-format, .github/workflows/check.yml, BUILD.bazel, WORKSPACE.bazel, hip_info.cpp, print_hip_info.cpp, src/decompress.hpp, src/decompress_test.cpp, toolchain/std_execution_available.cpp
Pull in @bazel_clang_format and @bazel_toolchain to allow use of
clang-format with a hermetic toolchain. This commit also adds a format
job to the check workflow.
To apply formatting to C/C++ source files, run
bazel run //:clang-format
Change-Id: I5f9c599cdb6b2ad9435728b6bb5f31cb2e61eebe
=> Add C++ format rules

.github/workflows/check.yml, BUILD.bazel, WORKSPACE.bazel, third_party/hip.BUILD.bazel, third_party/hip_cpu.BUILD.bazel, third_party/hipamd.BUILD.bazel, third_party/system_libs_linux_x86_64.BUILD.bazel
Pull in @buildifier_prebuilt to check format/lint rules. This commit
adds a buildifier job to the check workflow.
To apply formatting to Bazel files, run
bazel run //:buildifier.fix
Change-Id: Ia20b8ca1eb2d92722014eb84d313df2a8859538d
=> Add Bazel file format/lint rules

WORKSPACE.bazel
Running target `//:clang-format` would fail due to:
ERROR: action 'Copying files' is not up-to-date
where the out of date file was due to:
SUBCOMMAND: # @llvm_16_0_toolchain//:clang-format [action 'Copying
files', configuration:
9fc8a8262f58c1d22b9ca8421b92460c8b557b748071184ec95e106048b61999,
execution platform: @local_config_platform//:host]
This commit updates `@bazel_clang_format` so it not longer fails if
the clang-format binary target is not up-to-date.
Change-Id: I19bfc3146f6bdc454f94581bf303cb44535967b4
=> Fix error when running `//:clang-format` target

.bazelrc, .github/workflows/check.yml, WORKSPACE.bazel, src/huffman.hpp, src/huffman_test.cpp, toolchain/BUILD.bazel, toolchain/asan_feature_available.cpp, toolchain/runtime_failure.sh, toolchain/tsan_feature_available.cpp, toolchain/ubsan_feature_available.cpp
Add Clang 16.0 as the default C++ toolchain. Both GCC 12.2 and Clang
16.0 are tested in the Github check workflow. The test workflow also
verifies that sanitizer features `asan`, `tsan`, and `ubsan` are
available with Clang.
The creation of the huffman tree contained an expression without a well
defined order of evaluation, resulting in different behavior between GCC
and Clang. This is updated to use a well defined order and reflected in
the tests.
Also support building on MacOS, though not with sanitizers.
Change-Id: I2c02446a5e419fdc2e7b6af23a43c002f2343f08
=> Register Clang 16.0 as the default toolchain

.bazelrc, .clang-tidy, .github/workflows/check.yml, BUILD.bazel, WORKSPACE.bazel, src/.clang-tidy, src/BUILD.bazel, src/decompress.hpp, src/decompress_test.cpp, src/huffman.hpp, src/test/.clang-tidy, src/test/BUILD.bazel, src/test/decompress.cpp, src/test/huffman.cpp, toolchain/.clang-tidy
Pull in @bazel_clang_tidy to enable clang-tidy with a hermetic
toolchain. This job also adds a clang-tidy job to the check workflow.
To run clang-tidy on source files:
bazel build //... --config=clang-tidy
For clang-tidy checks that have fixes, those can be applied with
bazel run //:clang-tidy-fix
This commit also applies fixes and check suppressions to source files.
In order to allow different rulesets for test code, tests have been
moved into a separate test directory.
Change-Id: If22bbd78ae36068d9425898723db5480127e2ea2
=> Add clang-tidy configuration

src/huffman.hpp, src/test/huffman.cpp
Remove use of `std::priority_queue` on construction of a `code_table`.
Construction no longer creates a `std::vector` for each symbol. Instead,
the Huffman tree is created in-place.
In addition, this commit also:
* adds the `[[nodiscard]]` attribute to functions without side effects
* simplifies the `code_table` CTAD constraints
* requires a `Symbol` to be totally ordered
Change-Id: Ica17732f060dd101084feca36229c6496bc95cb1
=> Reduce allocations on `code_table` construction

src/BUILD.bazel, src/detail/huffman_storage.hpp, src/huffman.hpp
Instead of using `std::vector` directly as the underlying storage type
of `code_tree`, define `detail::huffman_storage` type. In this commit,
`detail::huffman_storage` inherits from `std::vector` and does not
change any behavior of `code_table`. However, this will simplify a
following commit that allows use of `std::array` as the storage type.
Change-Id: I27c29eda68f139aff8c3fbaa3f54c4a57ca1ab19
=> Separate out storage type for `code_table`

src/detail/huffman_storage.hpp, src/huffman.hpp, src/test/huffman.cpp, src/test/huffman_bench.cpp
If specified with a static extent, use `std::array` as the underlying
storage of a `code_table`, allowing it to be statically sized. This
commit also defines deduction guides to deduce the static size from an
input range.
Change-Id: I742cecd16c55e9d4be53d9d89b8096052685e215
=> Allow statically sized storage for `code_table`s

WORKSPACE.bazel, src/detail/huffman_storage.hpp, src/huffman.hpp, src/test/huffman.cpp
Allow construction of a `code_table` from an input range of symbols.
This is currently supported only for `code_table` types with dynamic
extent.
Change-Id: Ied4e27547d144995b692520ea879761b7b9e2691
=> Construct a `code_table` from a symbol sequence

.clang-tidy, src/detail/huffman_storage.hpp, src/huffman.hpp, src/test/huffman.cpp
Allow the capacity of a `code_table` with static extent to exceed the
size of the alphabet. This allows a `code_table` to be constructed from
a sequence of symbols at compile-time, provided the size of the alphabet
does not exceed the table capacity.
Change-Id: I629a87c8393fd7b2524d4ebe0afc8b7aa2ab2356
=> Allow excess capacity for static extent `code_table`s

.bazelrc, .clang-tidy, .github/workflows/check.yml, WORKSPACE.bazel, tools/BUILD.bazel
From a run on my local machine:
INFO: From Run clang-tidy on huffman/test/table_from_data_test.cpp:
===-------------------------------------------------------------------------===
clang-tidy checks profiling
===-------------------------------------------------------------------------===
Total Execution Time: 422.6479 seconds (422.6704 wall clock)
---User Time---   --System Time--   --User+System--   ---Wall Time---  --- Name ---
202.0039 ( 48.1%)   0.0885 (  3.7%)  202.0923 ( 47.8%)  202.1033 ( 47.8%)  bugprone-reserved-identifier
201.4224 ( 47.9%)   0.0697 (  2.9%)  201.4921 ( 47.7%)  201.5031 ( 47.7%)  readability-identifier-naming
3.4124 (  0.8%)   0.4181 ( 17.6%)   3.8304 (  0.9%)   3.8280 (  0.9%)  misc-confusable-identifiers
...
This commit updates @bazel_clang_tidy to propagate …
=> Disable very slow clang-tidy checks

huffman/src/code.hpp, huffman/test/BUILD.bazel, huffman/test/code_test.cpp, huffman/test/table_from_frequencies_test.cpp
`code::bit_view()` returns a view of the bits in a code as chars with
value `0` or `1`.
`operator::_c` provides simpler shorthand for creating a code
literal, which is particularly useful in tests:
assert(code{.bitsize = 3, .value = 0b010} == 010_c)
Change-Id: I1f4b938e76c29ce0a0414daddb0555251017606a
=> Define `code::bit_view()` and literal `_c`

.clang-tidy, huffman/BUILD.bazel, huffman/huffman.hpp, huffman/src/bit.hpp, huffman/src/code.hpp, huffman/src/detail/table_node.hpp, huffman/src/encoding.hpp, huffman/test/BUILD.bazel, huffman/test/bit_test.cpp, huffman/test/code_test.cpp
Define a distinct `bit` type, allowing strongly-typed bit operations on
`code` values.
`code::bit_view()` now returns of range of `bit` types instead of chars.
Change-Id: Iea9328d01d92a5b513c3644a442ceafa3f2ac89e
=> Define a `bit` type

huffman/src/detail/static_vector.hpp, huffman/src/detail/table_node.hpp, huffman/src/detail/table_storage.hpp, huffman/src/table.hpp, huffman/test/BUILD.bazel, huffman/test/table_from_contents_test.cpp
Define a constructor for `huffman::table` from an existing code-symbol
mapping:
huffman::table<char>{
huffman::mapping,
{{00000_c, '\4'},
{00001_c, 'x'},
{0001_c,  'q'},
{001_c,   'n'},
{01_c,    'i'},
{1_c,     'e'}};
This is primarily used in upcoming decoding tests. It avoids the need to
construct a table from data or frequencies and allows direct comparisons
to other Huffman decoding implementations.
Change-Id: If42c8d309eaab74fcdbfd5c68e51546eadac1e3f
=> Allow construction of a `table` from code-symbol map

WORKSPACE.bazel, toolchain/BUILD.bazel
Improve hermeticity for linux-x86_64 host platforms by using a Bootlin
toolchain provided sysroot with LLVM toolchains.
This applies to targets built with the LLVM toolchain - toolchain
binaries (e.g. `clang`) will still dynamically load system libraries
(e.g. `libc`).
Change-Id: I8d9c29266ec86c4d08a81d7c8ad9c5b953d1eb31
=> Link to Bootlin sysroot with LLVM toolchain

WORKSPACE.bazel, tools/llvm_toolchain.bzl, tools/llvm_toolchain_dependencies.bzl, tools/local_config_info.bzl
Wrap all tools from LLVM, replacing the dynamic loader with one from the
Bootlin toolchain sysroot. This allows use of Bootlin provided libraries
instead of relying on system libraries of the host (e.g. libc).
This commit updates @bazel_clang_tidy to add toolchain builtin include
directories to the ClangTidy command line.
Change-Id: I5369ee89d06004670f57df02d1bb745c44a6846c
=> Patch LLVM toolchain tools to use Bootlin sysroot libraries

.bazelrc, .vscode/settings.json, BUILD.bazel, WORKSPACE.bazel, toolchain/BUILD.bazel, tools/BUILD.bazel
Rename
`llvm_16_0_toolchain` -> `llvm_16_toolchain` and
`gcc_12_2_toolchain`  -> `gcc_12_2_toolchain`
until we decide we want to support different minor GCC or Clang
toolchain versions.
Change-Id: I5d1196bdf9d990764034775f558d2d14e413758d
Co-authored-by: Gary Miguel <garymm@garymm.org>
=> Simplify toolchain names

WORKSPACE.bazel
Both `-fsanitize-link-c++-runtime` and `--driver-mode=g++` can be used to
work around https://github.com/bazelbuild/bazel/issues/12797
but intent is clearer with `-fsanitize-link-c++-runtime`.
resolves #57
Change-Id: I8bbf9518b7587f67c274ed389e5153d66166b2f7
=> Change UBSan linkopt flag

huffman/BUILD.bazel, huffman/src/detail/base_view.hpp, huffman/src/table.hpp, huffman/test/table_find_code_test.cpp
Replace use of `views::transform` with a custom view type
`detail::base_view<V, B>` that casts a derived type (i.e. elements of
view `V`) to base `B`.
`detail::base_view<V, B>` requires the reference type of underlying view
`V` be a true reference, thus `detail::base_view<V, B>::iterator`
defines `operator->` to return a pointer to `B*`.
resolves #49
Change-Id: I2c9d14705bd5a0d8f7e562006913906d40c7fe86
=> Allow use of `operator->` with `huffman::table::const_iterator`

huffman/BUILD.bazel, huffman/src/detail/base_view.hpp, huffman/src/detail/iterator_interface.hpp
Define `huffman::detail::iterator_interface`, a CRTP helper class to
synthesize boiler-plate operations necessary to model
`std::random_access_iterator`. This allows `detail::base_view::iterator`
to define only the necessary basis operations, as well simplifying the
implementation of `bit_span::iterator` in a future commit.
Change-Id: I8fe5c4b00a905d60621e84f5396df90668d307a5
=> Use `iterator_interface` in `base_view::iterator` definition

WORKSPACE.bazel
update gcc toolchain
Change-Id: I9403ad449178aa0eb92c1169d0ee381c319e7d5a
=> update gcc toolchain

.github/workflows/check.yml
GitHub is throttling our jobs because we have so many. These seem like
the least important.
Change-Id: I8df8d538d303e3868d83f322002555ab20557f8f
=> rm build-without-terminfo GitHub checks

README.md, huffman/BUILD.bazel, huffman/huffman.hpp, huffman/src/bit_span.hpp, huffman/src/code.hpp, huffman/src/decode.hpp, huffman/test/BUILD.bazel, huffman/test/decode_test.cpp
Change-Id: I97309a7fd3c7059fe439fe516ba97920b53b5fcd
=> huffman decode

.github/workflows/check.yml, .github/workflows/ci.bazelrc
Change-Id: I2ee14831a7562c5735f20ccedd13fb2e887cbcdc
=> enable codecov in GH check

huffman/src/detail/table_storage.hpp, huffman/src/table.hpp, huffman/test/BUILD.bazel, huffman/test/table_canonicalize_test.cpp
huffman::table::canonicalize() updates the existing codes in a table to
canonical form for DEFLATE:
* All codes of a given bit length have lexicographically consecutive
values, in the same order as the symbols they represent;
* Shorter codes lexicographically precede longer codes.
Change-Id: Idc3dceefe1b5d17a54f1dab29155a499c7e1d138
=> define huffman::table::canonicalize()

.clang-tidy, WORKSPACE.bazel, huffman/src/bit_span.hpp, huffman/src/code.hpp
Update LLVM toolchain to 17.0.2 and resolve related TODOs.
Release notes for libc++ can be found here:
https://libcxx.llvm.org/ReleaseNotes/17.html
Change-Id: Idd5c68bb5f64285d379ed0c69a5022a79b5ab339
=> update clang to 17.0.2

WORKSPACE.bazel, toolchain/BUILD.bazel, toolchain/rules_cc-gcc-ubsan-no-sanitize-null.patch
Use of GCC with UBSan and the null, returns-nonnull-attribute,
nonnull-attribute checks will cause the compiler to reject valid code
due to use of the underlying GCC option -fno-delete-null-pointer-checks.
This commit patches rules_cc to disable these checks if a GCC compiler
is used with the ubsan feature.
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67762#c2
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71962
This change is needed by #89.
Change-Id: Ic0e5224850d8478aa92806a8f21248e979acce04
=> disable ubsan null checks with gcc

.clang-tidy, huffman/src/detail/table_node.hpp, huffman/src/table.hpp
Replace the frequency and node size fields of table node with a union of
an initialization struct and a decode struct. The initialization struct
contains the previously defined frequency and node size fields and is
used during table construction. The decode struct contains a single skip
value field.
table::find now uses the skip value if the iterator's element bitsize
does not match the code bitsize. This performs a skip to the next group
of elements with a larger bitsize instead of linear traversal of
elements.
Use of a union ensures that skip fields are set after construction as
constant expression context does not allow access to an inactive union
member. This allows re-use of the space without any risk of conflict,
since the skip fields are only used after construction and the …
=> use skip fields in table::find

huffman/src/detail/static_vector.hpp, huffman/src/detail/table_node.hpp, huffman/src/detail/table_storage.hpp, huffman/src/table.hpp, huffman/test/decode_test.cpp, huffman/test/table_canonicalize_test.cpp, huffman/test/table_find_code_test.cpp, huffman/test/table_from_contents_test.cpp, huffman/test/table_from_data_test.cpp
Remove use of std::reverse_iterator when iterating over table elements.
Instead, invoke reverse on the underlying table storage after
construction.
Change-Id: I45916a591f51298fff8b4012b9507b781021100e
=> store huffman table elements in forward order

huffman/BUILD.bazel, huffman/src/detail/table_storage.hpp, huffman/src/table.hpp, huffman/src/utility.hpp, huffman/test/BUILD.bazel, huffman/test/table_from_contents_test.cpp, huffman/test/table_from_symbol_bitsize_test.cpp
Add a constructor to huffman::table that takes a range of symbol-bitsize
tuples.
This commit also moves public tag types into a utility header.
Change-Id: Ia125173ce91e2e189c23de0956d9eaa7aa51762c
=> add huffman table constructor from symbol-bitsize range

.bazelrc
bazelrc: set --incompatible_strict_action_env
This keeps builds cache-compatible between different shells
(in particular the shell used by the VS Code build task and my
regular ZSH).
Change-Id: Ie854b618bc50e5ca668e0d0faa529a3737346510
=> bazelrc: set --incompatible_strict_action_env

huffman/src/bit_span.hpp, huffman/src/decode.hpp, huffman/test/bit_span_test.cpp, huffman/test/decode_test.cpp
bit_span: read least significant bit first
to match the DEFLATE format
Change-Id: I9f8a0329e1d37ce760ffb939ce329624872528db
=> bit_span: read least significant bit first

huffman/src/bit_span.hpp, huffman/src/utility.hpp, huffman/test/bit_span_test.cpp
bit_span: add pop and consume
will be useful when decoding a DEFLATE stream
Change-Id: I4ba8659230270f8e571fe70444d9f5c629a888a3
=> bit_span: add pop and consume

BUILD.bazel, WORKSPACE.bazel, huffman/test/BUILD.bazel, huffman/test/bit_span_test.cpp, src/test/BUILD.bazel, test_ut/BUILD.bazel, test_ut/test_ut_example.cpp, ut.hpp
Define the function `boost::ut::range_eq` that compares elements in two
ranges. If the elements are not equal, this function displays the first
mismatch in the two ranges or if one range is larger than another.
This commit also updates `boost-ut` to allow use of ranges in
parameterized tests.
resolves #106
Change-Id: I24b4f37927799c7eb3b68d3ac2ce159f60e3d94f
=> add `boost::ut::range_eq`

.vscode/launch.json, .vscode/tasks.json, huffman/src/bit_span.hpp, huffman/test/decode_test.cpp, src/BUILD.bazel, src/decompress.cpp, src/decompress.hpp, src/test/BUILD.bazel, src/test/decompress_test.cpp
decompress block type 00 - no compression
Change-Id: I5ceb11f5b6ba0ef63e250757747dab79c7958653
=> decompress block type 00 - no compression

WORKSPACE.bazel
update llvm toolchain repo
includes 17.0.2 for macos
Change-Id: I591c164d3e1feb4770d062ed915c0259d944fc39
=> update llvm toolchain repo

.clangd, README.md
fix clangd instructions
work around https://github.com/hedronvision/bazel-compile-commands-extractor/issues/140
Change-Id: I86a23ad7ffc699773a9219a3c766e22df0946479
=> fix clangd instructions

huffman/src/bit_span.hpp, huffman/test/bit_span_test.cpp
Define a default constructor for `bit_span`. Update `consume` to return
a reference.
Change-Id: I08edcc3e240a44a04b09a8ba787030665134f3a8
=> update `bit_span` constructors and `consume` member

test_ut/test_ut_example.cpp, ut.hpp
Change-Id: I5dca691416482ae27ab31bc176fd5217b8e3fd8f
=> define stream insertion for std::byte in tests

huffman/test/decode_test.cpp
Update decode test to construct a table in canonical form and fix the
associated test. This commit also adds additional decode test cases.
Change-Id: Ic46cbcee812f5812ab55f446c7d05c0e9e9d3e8a
=> fix decode test after always using DEFLATE canonicalization

src/test/BUILD.bazel, src/test/decompress_test.cpp, src/test/starfleet.html, tools/BUILD.bazel, tools/compressed_file.bzl, tools/deflate_compress.py
test data for fixed and dynamic huffman trees
and a script to generate it
I guess the nice way to do this would be to bring in rules_python and
generate the data in a genrule, or pull in zlib and have our test
generate the compressed data at run-time. We can add that later if
we find keeping the compressed and decompressed data in sync is annoying
enough.
Change-Id: Iaba4043956a2eb6fd0f51aef40414ae948a7311e
=> test data for fixed and dynamic huffman trees

README.md
Hey guys! Hedron Compile Commands Extractor author here. I saw your #111, @garymm, while catching up on https://github.com/hedronvision/bazel-compile-commands-extractor/issues/140. If you're going to run a build after, it might well be worth running it before, after. That way the extractor is more likely to hit a fresh header cache from the build and run faster :)
=> Build before and after compile commands extraction

huffman/src/table.hpp
All DEFLATE canonical codes of a given bitsize are lexicographically
consecutive values in the same order as the symbols they represent. As
a result, the skip field for the first code of a given bitsize can be
used to determine if an input code exists in the table in constant time.
This commit replaces the linear time search of all codes of a given
bitsize in huffman::table::find. Instead, the find method does the
following:
* if the input code bitsize is greater than the iterator code bitsize,
advance the iterator by the iterator skip field
* if the input code bitsize is less than the iterator code bitsize,
return the iterator as an error
* if the input code bitsize is equal to the iterator code bitsize:
- determine the distance from the iterator code value to the input
code value. If it …
=> use random access indexing in huffman::table::find

src/decompress.cpp, src/decompress.hpp, src/test/decompress_test.cpp
Caller passes in dst to decompress
This avoids allocation inside decompress.
Also:
* Doxygen style comments for public interface.
* Move decompress implementation to .cpp since it is no longer
templated.
* Move checking of final to the top of the loop.
Change-Id: I4afa1e306c5d20c1a83d3173292b77ab6e8fc01c
=> Caller passes in dst to decompress

.github/workflows/check.yml, .github/workflows/ci.bazelrc
also remove unnecessary remote_download_minimal. We're not using a
remote cache so it's pointless.
Change-Id: I375b456a064ccbd57d6cdc94f9b548371d92ddaf
=> GitHub: cache more things

.bazelrc, .github/workflows/check.yml, .github/workflows/ci.bazelrc
this save disk space and should help cache hit rates
=> improve caching in CI

README.md, src/decompress.cpp, src/decompress.hpp, src/test/decompress_test.cpp
remove chucnked output for now
It adds too much complexity. I want to focus on the basics.
Change-Id: I45c0da75d8a3c81eb20a982c8ccba6a1c87b2374
=> remove chucnked output for now

README.md, src/decompress.cpp, src/decompress.hpp, src/test/decompress_test.cpp
remove chunked output for now
It adds too much complexity. I want to focus on the basics.
Change-Id: I45c0da75d8a3c81eb20a982c8ccba6a1c87b2374
=> remove chunked output for now

src/decompress.cpp, src/decompress.hpp, src/test/decompress_test.cpp
return error for src too small
Change-Id: I745f447fb22a843257d1ae211a130cd39dad4ccc
=> return error for src too small

huffman/src/bit_span.hpp, huffman/src/decode.hpp, huffman/test/bit_span_test.cpp, src/decompress.cpp, src/decompress.hpp, src/test/BUILD.bazel, src/test/decompress_test.cpp, toolchain/tsan_feature_available.cpp
support decompressing fixed huffman blocks
Change-Id: I5a30394b46e113595336e89c954e03d3acb120fe
=> support decompressing fixed huffman blocks
